name: Kotlin Monorepo - Build and Release Apps

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      apps_dir:
        description: "Directory containing the apps"
        type: string
        default: "src/apps"
        required: false
      apps:
        description: "Comma-separated list of app names to build and deploy"
        type: string
        required: true
      github_app_token:
        description: "GitHub token for authentication"
        required: true
    secrets:
      GITOPS_TOKEN:
        required: true

jobs:
  check-bump:
    name: Check for bumped apps
    runs-on: ubuntu-latest
    outputs:
      apps_dir: ${{ steps.extract-apps.outputs.apps_dir }}
      bumped_apps: ${{ steps.extract-apps.outputs.apps }}
      repo: ${{ steps.set-repo.outputs.repo }}
      event_repo: ${{ steps.set-repo.outputs.event_repo }}
    steps:
      - name: Extract bumped apps
        id: extract-apps
        run: |
          APPS="${{ github.event.inputs.apps }}"
          echo "apps_dir=${{ github.event.inputs.apps_dir }}" >> $GITHUB_OUTPUT

          APPS_JSON=$(echo "$APPS" | tr ',' '\n' | awk '{$1=$1};1' | sed '/^$/d' | jq -R . | jq -s . | tr -d '\n')
          echo "apps=$APPS_JSON" >> $GITHUB_OUTPUT

      - name: Set lowercase repository names
        id: set-repo
        run: |
          echo "repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "event_repo=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  build-and-release:
    name: Build and release
    needs: check-bump
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.check-bump.outputs.bumped_apps) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ inputs.github_app_token }}

      - name: Get app version
        id: version
        run: |
          VERSION=$(grep 'version = ' "${{ needs.check-bump.outputs.apps_dir }}/${{ matrix.app }}/build.gradle.kts" | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.github_app_token }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          build-args: |
            APP=${{ matrix.app }}
            VERSION=${{ steps.version.outputs.version }}
          push: true
          tags: ghcr.io/${{ needs.check-bump.outputs.repo }}-${{ matrix.app }}:${{ steps.version.outputs.version }}

      - name: Save image digest
        run: echo "${{ steps.build.outputs.digest }}" > digest.txt

      - name: Upload image digests
        uses: actions/upload-artifact@v4
        with:
          name: image-digests-${{ matrix.app }}
          path: digest.txt

  pre-deploy:
    needs: [check-bump, build-and-release]
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.export-apps.outputs.apps }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: digests

      - uses: actions/checkout@v6
        with:
          path: local
          token: ${{ inputs.github_app_token }}

      - uses: actions/checkout@v6
        with:
          repository: ijskoud/homelab-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Prepare app list
        run: echo '${{ needs.check-bump.outputs.bumped_apps }}' > apps.json

      - name: Update deployment files for bumped apps
        run: |
          cd gitops
          APPS=$(cat ../apps.json | jq -r '.[]')

          for APP in $APPS; do
            DEPLOYMENT_DIR="apps/${{ needs.check-bump.outputs.event_repo }}-$APP"
            DEPLOYMENT_FILE="$DEPLOYMENT_DIR/deployment.yaml"

            DIGEST=$(cat ../digests/image-digests-$APP/digest.txt)
            APP_NAME="${{ needs.check-bump.outputs.event_repo }}-$APP"

            IMAGE="ghcr.io/${{ needs.check-bump.outputs.repo }}-$APP@$DIGEST"
            TEMPLATE_FILE="../local/deployment/deployment-$APP.template.yaml"

            if [ ! -f "$TEMPLATE_FILE" ]; then
              echo "❌ Template not found: $TEMPLATE_FILE"
              exit 1
            fi

            mkdir -p "$DEPLOYMENT_DIR"
            sed "s|DOCKER_IMAGE_SOURCE|$IMAGE|g" "$TEMPLATE_FILE" > "$DEPLOYMENT_FILE"

            echo "✅ Deployment written to $DEPLOYMENT_FILE"
          done

      - name: Commit changes to gitops repository
        run: |
          cd gitops
          APPS=$(cat ../apps.json | jq -r '.[]')

          git config user.email "noreply@github.com"
          git config user.name "versioning-release-bot"
          git add .

          if ! git diff --staged --quiet; then
            git commit -m "chore: update image(s) for app(s): $APPS from ${{ needs.check-bump.outputs.event_repo }}"
            git push
          else
            echo "No changes to commit for $APPS"
          fi
      - name: Export apps for deploy job
        id: export-apps
        run: echo "apps=${{ needs.check-bump.outputs.bumped_apps }}" >> $GITHUB_OUTPUT
